services:
  htpcmanager:
    container_name: htpcmanager
    image: linuxserver/htpcmanager:latest
    restart: unless-stopped
    ports:
    - 8085:8085/tcp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
