services:
  qflood:
    container_name: qflood
    image: hotio/qflood:latest
    restart: unless-stopped
    ports:
    - 3000:3000/tcp
    - 8080:8080/tcp
    volumes:
    - ./data/qFlood:/config
    - ./data/Downloads:/app/qBittorrent/downloads
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    - UMASK=002
    - FLOOD_AUTH=false
