services:
  markopolis:
    image: ghcr.io/rishikanthc/markopolis:2.0.0
    ports:
      - "${PORT:-8108}:80"
    environment:
      - MARKOPOLIS_DOMAIN=${MARKOPOLIS_DOMAIN:-}
      - MARKOPOLIS_FRONTEND_URL=${MARKOPOLIS_FRONTEND_URL:-}
      - MARKOPOLIS_TITLE=${MARKOPOLIS_TITLE:-Awesome Notes}
      - MARKOPOLIS_MD_PATH=/app/markdown
      - MARKOPOLIS_API_KEY=${MARKOPOLIS_API_KEY:-default_secret_key}
    volumes:
      - ./data:/app/markdown
    restart: unless-stopped
