services:
  homepage:
    container_name: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    ports:
    - 3000/tcp
    volumes:
    - ./data/apps/homepage:/app/config
    - /etc/localtime:/etc/localtime:ro
    environment:
    - PUID=15000
    - PGID=15000
    - TZ=America/Los_Angeles
    - UMASK=002
