services:
  plone:
    container_name: plone
    image: plone:latest
    restart: unless-stopped
    ports:
    - 8080/tcp
    volumes:
    - ./data/data:/data
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
