services:
  gotify:
    container_name: gotify
    image: gotify/server-arm7:latest
    restart: unless-stopped
    ports:
    - 9008:80/tcp
    volumes:
    - ./data/gotify:/app/data
    environment:
    - PUID=1000
    - PGID=100
    - TZ=America/New_York
    - UMASK=002
    - GOTIFY_DEFAULTUSER_NAME=admin
    - GOTIFY_DEFAULTUSER_PASS=admin123
