services:
  libredb-studio:
    container_name: libredb-studio
    image: ghcr.io/libredb/libredb-studio:latest
    restart: unless-stopped
    ports:
    - 3000:3000/tcp
    volumes:
    - ./data/app_data:/app/data
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
