services:
  minisatip:
    container_name: minisatip
    image: linuxserver/minisatip:latest
    restart: unless-stopped
    ports:
    - 8875:8875/tcp
    - 554:554/tcp
    - 1900:1900/udp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
    - RUN_OPTS=
