services:
  caddy:
    container_name: caddy
    image: caddy:latest
    restart: unless-stopped
    ports:
    - 80/tcp
    volumes:
    - ./data/data:/data
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
