services:
  lunalytics:
    image: ksjaay/lunalytics:latest
    container_name: lunalytics
    ports:
    - 2308:2308
    volumes:
    - ./data/lunalytics/data:/app/data
    - ./data/lunalytics/logs:/app/logs
    restart: unless-stopped
