services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
    - 9117:9117/tcp
    volumes:
    - ./data/config:/config
    - ./data/downloads:/downloads
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
    - AUTO_UPDATE=true
    - RUN_OPTS=
