services:
  airsonic:
    container_name: airsonic
    image: linuxserver/airsonic:latest
    restart: unless-stopped
    ports:
    - 4040:4040/tcp
    volumes:
    - ./data/Music:/music
    - ./data/Playlists:/playlists
    - ./data/Podcasts:/podcasts
    - ./data/Media:/media
    - ./data/Airsonic/:/config
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
    - CONTEXT_PATH=airsonic
    - JAVA_OPTS=-Xms256m -Xmx512m
