services:
  gotosocial:
    container_name: gotosocial
    image: superseriousbusiness/gotosocial:latest
    restart: unless-stopped
    ports:
    - 8080:8080/tcp
    volumes:
    - ./data/gotosocial_storage:/gotosocial/storage
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
    - GTS_HOST=localhost
    - GTS_DB_TYPE=sqlite
    - GTS_DB_ADDRESS=/gotosocial/storage/sqlite.db
    - GTS_LETSENCRYPT_ENABLED=false
