services:
  habridge:
    container_name: habridge
    image: linuxserver/habridge:latest
    restart: unless-stopped
    ports:
    - 8080:8080/tcp
    - 50000:50000/tcp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
    - SEC_KEY=
