services:
  homarr-secured:
    container_name: homarr-secured
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    ports:
    - 7575:7575/tcp
    volumes:
    - ./data/Homarr/configs:/app/data/configs
    - ./data/Homarr/icons:/app/public/icons
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Paris
    - UMASK=002
