services:
  emby:
    container_name: emby
    image: linuxserver/emby:latest
    restart: unless-stopped
    ports:
    - 8096:8096/tcp
    - 8920:8920/tcp
    volumes:
    - ./data/config:/config
    - ./data/tvshows:/data/tvshows
    - ./data/movies:/data/movies
    - ./data/lib:/opt/vc/lib
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002

# =========================================================================
# 🎮 Accélération Matérielle GPU (Optionnelle) :
# - Pour Intel QuickSync / AMD (VAAPI) :
#   devices:
#     - /dev/dri:/dev/dri
# - Pour NVIDIA (NVENC) :
#   deploy:
#     resources:
#       reservations:
#         devices:
#           - driver: nvidia
#             count: all
#             capabilities: [gpu]
# =========================================================================
