services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n:latest
    restart: unless-stopped
    ports:
    - 5678/tcp
    volumes:
    - ./data/apps/n8n:/home/node/.n8n
    - ./data/localtime:/etc/localtime
    environment:
    - PUID=1000
    - PGID=100
    - TZ=America/Los_Angeles
    - UMASK=002
    - GENERIC_TIMEZONE=America/Los_Angeles
