services:
  metube:
    container_name: metube
    image: alexta69/metube:latest
    restart: unless-stopped
    ports:
    - 8081:8081/tcp
    volumes:
    - ./data/Downloads:/downloads
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Paris
    - UMASK=002
