services:
  ihatemoney:
    container_name: ihatemoney
    image: ihatemoney/ihatemoney:latest
    environment:
      - DEBUG=False
      - ACTIVATE_ADMIN_DASHBOARD=False
      - ACTIVATE_DEMO_PROJECT=True
      - ALLOW_PUBLIC_PROJECT_CREATION=True
      - BABEL_DEFAULT_TIMEZONE=${TZ:-Europe/Paris}
      - MAIL_DEFAULT_SENDER=admin@example.com
      - SECRET_KEY=${SECRET_KEY:-ihatemoney_secret_key_change_me}
      - SESSION_COOKIE_SECURE=False
      - SHOW_ADMIN_EMAIL=True
      - SQLALCHEMY_DATABASE_URI=sqlite:////database/ihatemoney.db
      - SQLALCHEMY_TRACK_MODIFICATIONS=False
      - ENABLE_CAPTCHA=False
    volumes:
      - ./data:/database
    ports:
      - "${PORT:-8230}:8000"
    restart: unless-stopped
