services:
  netbootxyz:
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Athens
    - PORT_RANGE=30000:30010
    - SUBFOLDER=/
    volumes:
    - ./data/netbootxyz/config:/config
    - ./data/netbootxyz/assets:/assets
    ports:
    - 3300:3000
    - 369:69/udp
    - 38080:80
    restart: unless-stopped
