services:
  fail2ban:
    container_name: fail2ban
    image: linuxserver/fail2ban:latest
    restart: unless-stopped
    ports:
    - 80:80/tcp
    volumes:
    - ./data/config:/config
    - ./data/log:ro:/var/log:ro
    - ./data/airsonic:ro:/remotelogs/airsonic:ro
    - ./data/apache2:ro:/remotelogs/apache2:ro
    - ./data/authelia:ro:/remotelogs/authelia:ro
    - ./data/emby:ro:/remotelogs/emby:ro
    - ./data/filebrowser:ro:/remotelogs/filebrowser:ro
    - ./data/homeassistant:ro:/remotelogs/homeassistant:ro
    - ./data/lighttpd:ro:/remotelogs/lighttpd:ro
    - ./data/nextcloud:ro:/remotelogs/nextcloud:ro
    - ./data/nginx:ro:/remotelogs/nginx:ro
    - ./data/nzbget:ro:/remotelogs/nzbget:ro
    - ./data/overseerr:ro:/remotelogs/overseerr:ro
    - ./data/prowlarr:ro:/remotelogs/prowlarr:ro
    - ./data/radarr:ro:/remotelogs/radarr:ro
    - ./data/sabnzbd:ro:/remotelogs/sabnzbd:ro
    - ./data/sonarr:ro:/remotelogs/sonarr:ro
    - ./data/unificontroller:ro:/remotelogs/unificontroller:ro
    - ./data/vaultwarden:ro:/remotelogs/vaultwarden:ro
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
    - VERBOSITY=-vv
