services:
  tt-rss:
    container_name: tt-rss
    image: lunik1/tt-rss:latest
    restart: unless-stopped
    ports:
    - 80/tcp
    volumes:
    - ./data/tt-rss:/config
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
