services:
  healthchecks:
    container_name: healthchecks
    image: linuxserver/healthchecks:latest
    restart: unless-stopped
    ports:
    - 8000:8000/tcp
    - 2525:2525/tcp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
    - SECRET_KEY=
    - SITE_ROOT=
    - SITE_NAME=
    - SUPERUSER_EMAIL=
    - SUPERUSER_PASSWORD=
    - ALLOWED_HOSTS=
    - APPRISE_ENABLED=False
    - CSRF_TRUSTED_ORIGINS=
    - DEBUG=True
    - DEFAULT_FROM_EMAIL=
    - EMAIL_HOST=
    - EMAIL_PORT=
    - EMAIL_HOST_USER=
    - EMAIL_HOST_PASSWORD=
    - EMAIL_USE_TLS=
    - INTEGRATIONS_ALLOW_PRIVATE_IPS=
    - PING_EMAIL_DOMAIN=
    - RP_ID=
    - SITE_LOGO_URL=
