services:
  logzio-metrics-collector:
    container_name: logzio-metrics-collector
    image: logzio/docker-collector-metrics:latest
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./data/cgroup:/hostfs/sys/fs/cgroup
    - ./data/proc:/hostfs/proc
    - ./data/config:/hostfs
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
    - LOGZIO_TOKEN=REPLACE-LOGZIO-TOKEN-HERE
    - LOGZIO_MODULES=system,docker
