services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: always
    ports:
    - 8888:8080/tcp
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
