services:
  homebridge:
    container_name: homebridge
    image: homebridge/homebridge:latest
    restart: unless-stopped
    volumes:
    - ./data/homebridge:/homebridge
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/New_York
    - UMASK=002
    - HOMEBRIDGE_CONFIG_UI=1
    - HOMEBRIDGE_CONFIG_UI_PORT=8581
