name: rabbitmq
x-rmq:
  build: .
  image: miget-rabbitmq:local
  restart: unless-stopped
services:
  rmq-1:
    build: .
    image: miget-rabbitmq:local
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - rabbitmq-diagnostics
      - -q
      - ping
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    hostname: rmq-1
    environment:
      RABBITMQ_NODENAME: rabbit@rmq-1
    ports:
    - 5000:5000
    - '5672'
    - '4369'
    - '25672'
    volumes:
    - ./data/rmqdata-1:/var/lib/rabbitmq/mnesia
  rmq-2:
    build: .
    image: miget-rabbitmq:local
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - rabbitmq-diagnostics
      - -q
      - ping
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    hostname: rmq-2
    environment:
      RABBITMQ_NODENAME: rabbit@rmq-2
    ports:
    - '5000'
    - '5672'
    - '4369'
    - '25672'
    volumes:
    - ./data/rmqdata-2:/var/lib/rabbitmq/mnesia
  rmq-3:
    build: .
    image: miget-rabbitmq:local
    restart: unless-stopped
    healthcheck:
      test:
      - CMD
      - rabbitmq-diagnostics
      - -q
      - ping
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    hostname: rmq-3
    environment:
      RABBITMQ_NODENAME: rabbit@rmq-3
    ports:
    - '5000'
    - '5672'
    - '4369'
    - '25672'
    volumes:
    - ./data/rmqdata-3:/var/lib/rabbitmq/mnesia
volumes:
  rmqdata-1: null
  rmqdata-2: null
  rmqdata-3: null
