services:
  planka:
    container_name: planka
    image: linuxserver/planka:latest
    restart: unless-stopped
    ports:
    - 1337:1337/tcp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
    - BASE_URL=https://planka.example.com
    - DATABASE_URL=postgresql://user:password@planka-db:5432/planka
    - DEFAULT_ADMIN_EMAIL=demo@demo.demo
    - DEFAULT_ADMIN_USERNAME=demo
    - DEFAULT_ADMIN_PASSWORD=demo
    - DEFAULT_ADMIN_NAME=Demo User
    - SECRET_KEY=notasecretkey
    - TRUST_PROXY=false
    - DEFAULT_LANGUAGE=en-US
