services:
  opc-router:
    image: opcrouter/runtime:latest
    restart: unless-stopped
    ports:
    - 49420:49420
    - 8080:8080
    - 8081:8081
    environment:
    - OR_I_ACCEPT_EULA=${OR_I_ACCEPT_EULA}
    - INITIAL_USERNAME=${INITIAL_USERNAME}
    - INITIAL_PASSWORD=${INITIAL_PASSWORD}
    volumes:
    - type: volume
      source: ./data/opcrouter-configdb
      target: /data/database
    - type: volume
      source: ./data/opcrouter-inray
      target: /inray
    - type: volume
      source: ./data/opcrouter-logs
      target: /var/log/opcrouter
volumes:
  opcrouter-configdb: null
  opcrouter-inray: null
  opcrouter-logs: null
