services:
  fireshare:
    container_name: fireshare
    image: shaneisrael/fireshare:latest
    restart: unless-stopped
    ports:
    - 8888:80
    volumes:
    - ./data/fireshare/data:/data
    - ./data/fireshare/processed:/processed
    - ./data/fireshare/videos:/videos
    environment:
    - ADMIN_USERNAME=fireadmin
    - ADMIN_PASSWORD=firepwd
    - SECRET_KEY=replace_this_with_some_random_string0x0
    - MINUTES_BETWEEN_VIDEO_SCANS=1
    - PUID=998
    - PGID=100
