services:
  qemu-static:
    container_name: qemu-static
    image: linuxserver/qemu-static:latest
    restart: unless-stopped
    ports:
    - 80:80/tcp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
