services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
    - 8265:8265
    - 8266:8266
    - 8267:8267
    - 8268:8268
    environment:
    - TZ=Europe/Athens
    - PUID=${PUID}
    - PGID=${PGID}
    - UMASK_SET=002
    - serverIP=0.0.0.0
    - serverPort=8266
    - webUIPort=8265
    - internalNode=true
    - nodeID=MyInternalNode
    volumes:
    - ./data/tdarr/server:/app/server
    - ./data/tdarr/configs:/app/configs
    - ./data/logs:/app/logs
    - ./data/media:/media
    - ./data/transcode_cache:/temp
