services:
  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
    - PUID=65534
    - PGID=65534
    - UMASK_SET=022
    - RPC_PORT=6800
    - LISTEN_PORT=6888
    - DISK_CACHE=64M
    - IPV6_MODE=false
    - UPDATE_TRACKERS=true
    - CUSTOM_TRACKER_URL=
    - TZ=Europe/Athens
    volumes:
    - ./data/aria2-pro:/config
    - ./data/Downloads:/downloads
    network_mode: bridge
    ports:
    - 6800:6800
    - 6888:6888
    - 6888:6888/udp
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    environment:
    - PUID=1000
    - PGID=1000
    - ARIA2RPCPORT=6800
    - RPC_SECRET=P3TERX
    command: --port 6880 --ipv6
    network_mode: bridge
    ports:
    - 6880:6880
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 1m
