services:
  paste-bin:
    container_name: hasty-paste
    image: ghcr.io/enchant97/hasty-paste:latest
    restart: unless-stopped
    volumes:
    - ./data:/app/data
    ports:
    - "${PORT:-9800}:8000"
