services:
  codex:
    image: docker.io/ajslater/codex
    container_name: codex
    volumes:
    - ./data/codex:/config
    - ./data/comics:/comics:ro
    ports:
    - 9810:9810
    restart: on-failure
