name: ollama
services:
  ollama:
    image: ollama/ollama:0.30.8
    restart: unless-stopped
    environment:
      OLLAMA_HOST: 0.0.0.0:5000
    ports:
    - 5000:5000
    volumes:
    - ./data/models:/root/.ollama
volumes:
  models: null

# =========================================================================
# 🎮 Accélération Matérielle GPU (Optionnelle) :
# - Pour Intel QuickSync / AMD (ROCm) :
#   devices:
#     - /dev/dri:/dev/dri
# - Pour NVIDIA (CUDA) :
#   deploy:
#     resources:
#       reservations:
#         devices:
#           - driver: nvidia
#             count: all
#             capabilities: [gpu]
# =========================================================================
