services:
  wowza:
    container_name: wowza
    image: sameersbn/wowza:4.1.2-8
    restart: unless-stopped
    ports:
    - 1935/tcp
    - 8086/tcp
    - 8087/tcp
    - 8088/tcp
    volumes:
    - ./data/var_lib_wowza:/var/lib/wowza
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
    - WOWZA_ACCEPT_LICENSE=yes
    - WOWZA_KEY=
