services:
  mailpile:
    container_name: mailpile
    image: rroemhild/mailpile
    volumes:
    - ./data/mailpile:/root/.local/share/Mailpile
    - ./data/mailpile/gnu:/root/.gnupg
    ports:
    - 33411:33411
    restart: unless-stopped
