services:
  hivekeep:
    container_name: hivekeep
    image: ghcr.io/marlburrow/hivekeep:latest
    restart: unless-stopped
    ports:
    - 3000:3000/tcp
    volumes:
    - ./data:/app/data
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
    - HOST=0.0.0.0
    - PUBLIC_URL=http://localhost:3000
