services:
  syncserver:
    container_name: syncserver
    image: mozilla/syncserver:latest
    restart: unless-stopped
    ports:
    - 5000/tcp
    volumes:
    - ./data/apps/syncserver:/data
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
    - SYNCSERVER_PUBLIC_URL=https://syncserver.depot.lan
    - SYNCSERVER_SECRET_FILE=/data/secret_key
    - SYNCSERVER_SQLURI=sqlite:////data/syncserver.db
    - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
    - SYNCSERVER_FORCE_WSGI_ENVIRON=false
    - PORT=5000
