services:
  chevereto:
    container_name: chevereto
    image: nmtan/chevereto:latest
    restart: unless-stopped
    ports:
    - 80/tcp
    volumes:
    - ./data/var_www_html_images:/var/www/html/images
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
    - CHEVERETO_DB_HOST=
    - CHEVERETO_DB_USERNAME=
    - CHEVERETO_DB_PASSWORD=
    - CHEVERETO_DB_NAME=
    - CHEVERETO_DB_PREFIX=
