services:
  dokuwiki:
    container_name: dokuwiki
    image: linuxserver/dokuwiki:latest
    restart: unless-stopped
    ports:
    - 80:80/tcp
    - 443:443/tcp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
