services:
  homeassistant:
    container_name: homeassistant
    image: linuxserver/homeassistant:latest
    restart: unless-stopped
    ports:
    - 8123:8123/tcp
    volumes:
    - ./data/config:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
