services:
  beets:
    container_name: beets
    image: linuxserver/beets:latest
    restart: unless-stopped
    ports:
    - 8337:8337/tcp
    volumes:
    - ./data/config:/config
    - ./data/music:/music
    - ./data/downloads:/downloads
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - UMASK=002
