services:
  influxdb:
    container_name: influxdb
    image: influxdb:2-alpine
    volumes:
    - ./data/influxdb2:/var/lib/influxdb2:rw
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USER:-admin}
    - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-adminpassword123}
    - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-noos}
    - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-metrics}
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN:-noos-admin-token-super-secret}
    ports:
    - "${PORT:-8086}:8086"
    restart: unless-stopped
