version: '3'

services:
  tooljet:
    container_name: tooljet
    image: tooljet/tooljet-ce:latest
    restart: unless-stopped
    ports:
      - "${PORT:-8082}:80"
    depends_on:
      - postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
      TOOLJET_HOST: "${TOOLJET_HOST:-http://localhost:8082}"
      LOCKBOX_MASTER_KEY: "${LOCKBOX_MASTER_KEY:-0000000000000000000000000000000000000000000000000000000000000000}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:-secret_key_base_32_characters_min}"
      PG_DB: "${PG_DB:-tooljet_production}"
      PG_USER: "${PG_USER:-postgres}"
      PG_HOST: postgres
      PG_PASS: "${PG_PASS:-postgres}"
      CHECK_FOR_UPDATES: "false"
    command: npm run start:prod

  postgres:
    container_name: tooljet-postgres
    image: postgres:13
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "${PG_DB:-tooljet_production}"
      POSTGRES_USER: "${PG_USER:-postgres}"
      POSTGRES_PASSWORD: "${PG_PASS:-postgres}"
