services:
  omada-controller:
    container_name: omada-controller
    image: mbentley/omada-controller:latest
    restart: unless-stopped
    ports:
    - 8088:8088/tcp
    - 8043:8043/tcp
    - 27001:27001/udp
    - 27002:27002/tcp
    - 29810:29810/udp
    - 29811:29811/tcp
    - 29812:29812/tcp
    - 29813:29813/tcp
    volumes:
    - ./data/Omada:/config
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Europe/Paris
    - UMASK=002
