services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    restart: unless-stopped
    ports:
    - 3000:3000/tcp
    - 222:22/tcp
    volumes:
    - ./data/Gitea:/data
    - ./data/ /etc/timezone:/etc/timezone:ro
    - ./data/localtime:/etc/localtime:ro
    environment:
    - PUID=1000
    - PGID=100
    - TZ=Europe/Paris
    - UMASK=002
